spring:
  application:
    name: cryptotrading
  datasource:
    url: jdbc:h2:mem:cryptodb
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/init-data.sql
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: crypto

task:
  executor:
    maxPoolSize: 5
